### ISSUE TITLE
Visualização de múltiplas instâncias

### ISSUE THREAD

**Issue by felipebraz** [luizf-lf/fluig-monitor#30]
Possuo vários clientes que utilizam o fluig em load balance e seria maravilhoso poder monitorar os nós do balanceamento além só do servidor principal (o que respondeu a API do monitor).

**Comment by luizf-lf** [comment]
Olá @felipebraz, peço desculpas pela demora na resposta. As APIs de monitoramento realmente reportam os recursos de apenas um dos nós, conforme a [documentação](https://tdn.totvs.com/pages/releaseview.action?pageId=284881802). Ainda não tive a oportunidade de simular um ambiente em load balance, mas estou planejando preparar um ambiente para adaptar a ferramenta para este cenário.

**Comment by felipebraz** [comment]
Me desculpe a demora também, sem problemas, ansioso por novidades.
