### ISSUE TITLE
.env-example not found

### ISSUE THREAD

**Issue by gabrielsohn** [luizf-lf/fluig-monitor#5]
Ola Luiz, tudo bem?

Estou tentando testar, porém o prisma está acusando falta do database url.

Pelo que vi ele está buscando a informação de um .env mas não encontrei o modelo de exemplo.

Também não readme não encontrei informação de como configurar e se é necessário um banco de dados instalado para rodar a aplicação.

**Comment by luizf-lf** [comment]
Olá Gabriel, 

O repositório já contém sim um arquivo .env.example, o mesmo está na raiz do projeto. Basta criar uma cópia e renomear apenas para .env, que, quando o app for inicializado em modo dev, o prisma irá criar o banco de dados dentro da pasta .prisma na raiz do projeto e realizar as migrações automaticamente.
O app usa o SQLite, portanto, não é necessária nenhuma configuração adicional.

Mas realmente vi que não me atentei a documentar estes detalhes no arquivo README e vou incluir essas informações.

Caso ainda persistir o erro ao inicializar a aplicação, favor enviar evidencias para que eu consiga reproduzir.
Se possível, informar qual sistema operacional está utilizando e a versão do mesmo.

**Comment by luizf-lf** [comment]
Outro detalhe, Gabriel,

Vi que você fez um fork do meu repositório, e vi que no seu fork realmente não consta um arquivo .env.example pois o mesmo está desatualizado, com o ultimo commit feito por mim sendo em 29/07/22, e o arquivo .env.example foi adicionado no meu repositório no dia 22/09/22.
Caso estiver testando pelo seu fork, sugiro que o atualize e teste novamente.

**Comment by gabrielsohn** [comment]
Obrigado pelo retorno @luizf-lf ! Realmente encontrei o arquivo aqui na sua branch atual. Dou a issue como resolvida.
