### ISSUE TITLE
Ferramenta não busca dados

### ISSUE THREAD

**Issue by aldimar-junior** [luizf-lf/fluig-monitor#6]
Bom dia, 

Estou tentando utilizar a ferramenta e instalei seguindo o passo a passo utilizando `Yarn`, ao abrir a aplicação fui recebido com um erro que aparentemente não impacta no funcionamento, foi algo relacionado a renderer, porém quando tento criar um ambiente e clico em testar conexão ele retorna falando que não conseguiu conectar e pede que eu verifique a URL, utilizando o `dev-tools` pude ver que ele dispara dois pings, um com sucesso e outro com falha:
![image](https://user-images.githubusercontent.com/98884282/207073332-194ba3bd-3f70-40bf-bc7d-246887665536.png)

sendo assim ignorei a falha do primeiro ping e salvei o ambiente, chegando na pagina "principal" ele consta que o ambiente está online e fica disparando pings mostrando o tempo de resposta porém ele não puxa nenhum dado do fluig, fica apenas disparando pings:
<img width="960" alt="electron_s8w86qywID" src="https://user-images.githubusercontent.com/98884282/207073887-dda90fc4-76ab-4359-a5b4-165fb9372ba9.png">

Coloquei para puxar de 15 em 15 minutos e mesmo após esperar vários intervalos nada aparece, nenhum erro no console e nada nas requisições.

Algo que fiz de errado ou esqueci de fazer durante o processo de instalação ou é problema da versão atual?

**Comment by aldimar-junior** [comment]
Atualização, recebi os seguintes erros/avisos no console:
![image](https://user-images.githubusercontent.com/98884282/207074988-6920b978-6412-4d64-af0a-1197d607886c.png)

Esses caminhos que a ferramenta está tentado realizar requisições não existem no meu ambiente, **Fluig 1.8.0**.

**Comment by luizf-lf** [comment]
Bom dia, Aldimar,

Este erro (403) retornado no console indica que provavelmente o usuário aplicativo utilizado não possui permissões nas APIs de estatísticas, monitor e licenças.
Após o cadastro do ambiente, estes dados são coletados pela primeira vez, porém, devido a falta de permissão, os mesmos não foram coletados.
Para corrigir este erro, defina o usuário aplicativo criado para o monitor como administrador, ou libere as permissões individualmente nas APIs através do painel de controle.

Em breve vou atualizar a documentação sobre este quesito, pois ainda não documentei sobre este ponto.
Inclusive, tenho mapeado uma melhoria para validar no momento do cadastro se o usuário aplicativo utilizado possui permissões sobre estas APIs para evitar este erro de permissão.

**Comment by aldimar-junior** [comment]
É, era isso mesmo, agora tirando uns erros de front a aplicação está funcionando perfeitamente!
