### ISSUE TITLE
Minimize to system tray feature

### ISSUE THREAD

**Issue by msmosso** [luizf-lf/fluig-monitor#7]
It would be awesome if we have the possibility to minimize the icon to the system tray.

**Comment by luizf-lf** [comment]
@msmosso, your suggestion has been marked as an "enhancement", and will be implemented on future releases. 

Just so I can be sure about this feature, the ideia is that the app should "disappear" from the taskbar when minimised and keep running on the background as a system tray icon, right?
I've seen a few apps doing this with the "close" button.
Anyways, when implemented, this feature will be configurable via the app settings panel.

**Comment by msmosso** [comment]
@luizf-lf Exactly! I think it would be a great addition.

**Comment by luizf-lf** [comment]
@msmosso This feature has been implemented and is available on the v0.4.0 preview release (https://github.com/luizf-lf/fluig-monitor/releases/tag/v0.4.0)
